# Generated by Django 2.1 on 2018-08-24 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='id',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shorturl',
            name='unique_id',
            field=models.SlugField(blank=True, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
