# Generated by Django 2.1 on 2018-08-25 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_auto_20180824_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='shortened_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.URLField(),
        ),
    ]
